# Generated by Django 6.0.6 on 2026-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplimit',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
