// <auto-generated />
using DLL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DLL.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DLL.Models.CryptoMonet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("symbol")
                        .IsUnique();

                    b.ToTable("CryptoMonet");
                });

            modelBuilder.Entity("DLL.Models.Quote", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Quote");
                });

            modelBuilder.Entity("DLL.Models.QuoteName", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("QuoteName");
                });

            modelBuilder.Entity("DLL.Models.Quote", b =>
                {
                    b.HasOne("DLL.Models.CryptoMonet", null)
                        .WithOne("quote")
                        .HasForeignKey("DLL.Models.Quote", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DLL.Models.QuoteName", b =>
                {
                    b.HasOne("DLL.Models.Quote", null)
                        .WithOne("USD")
                        .HasForeignKey("DLL.Models.QuoteName", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DLL.Models.CryptoMonet", b =>
                {
                    b.Navigation("quote")
                        .IsRequired();
                });

            modelBuilder.Entity("DLL.Models.Quote", b =>
                {
                    b.Navigation("USD")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
